/**
 * Coverage and source-quality report.
 *
 * Writes docs/COVERAGE.md and prints the same table. A dataset built by many hands needs
 * one place that says plainly what is missing and how well sourced the rest is —
 * otherwise a country absent from a chart is indistinguishable from a country with no
 * ministries, and a tier-3 guess looks exactly like a decree.
 *
 * Usage: npm run report:coverage
 */
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

import { loadDataset, valuesOf } from './lib/load.ts';
import { checkDataset } from './lib/rules.ts';
import { countBySeverity } from './lib/issues.ts';
import { DOCS_DIR, rel } from './lib/paths.ts';
import { deriveCountrySummary } from './lib/derive.ts';
import { CURATION_BATCHES, EU27, batchOf } from './lib/scope.ts';

const today = process.env.GOV_ATLAS_TODAY ?? new Date().toISOString().slice(0, 10);

const dataset = await loadDataset();
const issues = [...dataset.issues, ...checkDataset(dataset, { today })];
const { errors, warnings } = countBySeverity(issues);

const countries = valuesOf(dataset.countries);
const cabinets = valuesOf(dataset.cabinets);

interface Row {
  iso2: string;
  batch: string;
  name: string;
  ministries: string;
  seats: string;
  grade: string;
  tier1: string;
  sources: string;
  cabinet: string;
}

const rows: Row[] = [];

for (const iso2 of EU27) {
  const batch = batchOf(iso2)?.id ?? '—';
  const country = countries.find(({ value }) => value.iso2 === iso2);

  if (!country) {
    rows.push({
      iso2,
      batch,
      name: '_not started_',
      ministries: '—',
      seats: '—',
      grade: '—',
      tier1: '—',
      sources: '—',
      cabinet: '—',
    });
    continue;
  }

  const forCountry = cabinets.filter(({ value }) => value.country === iso2);
  const current =
    forCountry.find(({ value }) => value.left_office === null) ??
    forCountry.sort((a, b) => b.value.took_office.localeCompare(a.value.took_office))[0];

  if (!current) {
    rows.push({
      iso2,
      batch,
      name: country.value.name_en,
      ministries: '—',
      seats: '—',
      grade: '—',
      tier1: '—',
      sources: '0',
      cabinet: '_no cabinet file_',
    });
    continue;
  }

  const summary = deriveCountrySummary(country.value, current.value, today);
  rows.push({
    iso2,
    batch,
    name: summary.name_en,
    ministries: String(summary.ministries_count),
    seats: String(summary.cabinet_seats_count),
    grade: summary.quality.grade,
    tier1: `${Math.round(summary.quality.tier1_share * 100)}%`,
    sources: String(summary.quality.sources_total),
    cabinet: `${summary.cabinet_id}${summary.left_office === null ? '' : ' (former)'}`,
  });
}

const covered = rows.filter((row) => row.ministries !== '—');
const columns: { key: keyof Row; header: string }[] = [
  { key: 'iso2', header: 'ISO' },
  { key: 'batch', header: 'Batch' },
  { key: 'name', header: 'Country' },
  { key: 'ministries', header: 'Ministries' },
  { key: 'seats', header: 'Cabinet seats' },
  { key: 'grade', header: 'Grade' },
  { key: 'tier1', header: 'Tier-1 share' },
  { key: 'sources', header: 'Sources' },
  { key: 'cabinet', header: 'Cabinet' },
];

const table = [
  `| ${columns.map((column) => column.header).join(' | ')} |`,
  `| ${columns.map(() => '---').join(' | ')} |`,
  ...rows.map((row) => `| ${columns.map((column) => row[column.key]).join(' | ')} |`),
].join('\n');

const batchProgress = CURATION_BATCHES.map((batch) => {
  const done = batch.countries.filter((iso2) =>
    covered.some((row) => row.iso2 === iso2),
  ).length;
  return `| ${batch.id} | ${batch.label} | ${done}/${batch.countries.length} | ${batch.countries.join(', ')} |`;
}).join('\n');

// No generation date and no clock anywhere in this document: it is a pure function of the
// contents of data/, so CI can require the committed copy to match what the data produces. A
// timestamp would make that check fail every day for no reason and get switched off.
const document = `# Coverage

<!-- Generated by \`npm run report:coverage\`. Do not edit by hand. -->

${covered.length} of ${EU27.length} target countries curated.

Validation: ${errors} error(s), ${warnings} warning(s).

## Grades

- **A** — every counted ministry rests on a legal instrument (tier 1).
- **B** — every counted ministry rests on an official publication (tier 1 or 2).
- **C** — at least one counted ministry rests only on a secondary source.

Grades describe the evidence behind the headline count, not the count's political
significance. See [METHODOLOGY.md](METHODOLOGY.md) for what is counted and why.

## By country

${table}

## By curation batch

| Batch | Scope | Curated | Countries |
| --- | --- | --- | --- |
${batchProgress}
`;

await mkdir(DOCS_DIR, { recursive: true });
const target = path.join(DOCS_DIR, 'COVERAGE.md');
await writeFile(target, document, 'utf8');

console.log(table);
console.log('');
console.log(`${covered.length}/${EU27.length} target countries curated. Wrote ${rel(target)}.`);
